// Generates supabase/seed.sql and templates/*.json from scripts/templates.mjs.
// Run: node scripts/build-seed.mjs
import { writeFileSync, mkdirSync } from "node:fs";
import { businesses } from "./templates.mjs";

mkdirSync("templates", { recursive: true });
const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
let sql = `-- Generated by scripts/build-seed.mjs. Run AFTER schema.sql.
-- Inserts the 10 checklists. Safe to re-run: existing rows are updated (checklist text only; manager info and links are kept).
insert into businesses (slug, name, location, template) values\n`;
sql += businesses.map((b) => {
  writeFileSync(`templates/${b.slug}.json`, JSON.stringify(b.template, null, 2) + "\n");
  return `  (${q(b.slug)}, ${q(b.name)}, ${q(b.location)}, ${q(JSON.stringify(b.template))}::jsonb)`;
}).join(",\n");
sql += `\non conflict (slug) do update set template = excluded.template, name = excluded.name, location = excluded.location;\n`;
writeFileSync("supabase/seed.sql", sql);
console.log(`Wrote supabase/seed.sql and ${businesses.length} template files.`);
