// Local test harness (NOT used in production). Fakes Supabase REST, SendGrid and the Claude API in memory,
// serves public/ and mounts the real functions at their /api paths. Run: node scripts/dev-fake.mjs
import http from "node:http";
import { readFileSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";

const PORT = 8787;
process.env.SUPABASE_URL = `http://127.0.0.1:${PORT}/fake-supabase`;
process.env.SUPABASE_SERVICE_KEY = "fake";
process.env.SENDGRID_API_KEY = "fake"; process.env.FROM_EMAIL = "test@example.com";
process.env.ANTHROPIC_API_KEY = "fake";
process.env.SITE_URL = `http://127.0.0.1:${PORT}`; process.env.ADMIN_KEY = "adminkey";

// ---- seed the fake DB from seed.sql via templates.mjs
const { businesses } = await import("./templates.mjs");
const db = { businesses: businesses.map((b, i) => ({ id: `b${i + 1}`, ...b, manager_name: "Test Manager", manager_email: `m${i + 1}@example.com`, access_key: `key${i + 1}`, active: true })), weeks: [] };
export const sent = [];
let nextId = 1;

function parseFilters(sp) {
  const f = [];
  for (const [k, v] of sp) {
    if (["order", "limit", "on_conflict", "select"].includes(k)) continue;
    const m = v.match(/^(eq|lt|gte|is|neq)\.(.*)$/); if (!m) continue;
    let val = m[2]; if (m[1] === "is") val = val === "null" ? null : val === "true";
    f.push({ k, op: m[1], val });
  }
  return (row) => f.every(({ k, op, val }) => {
    const x = row[k] ?? null;
    if (op === "eq") return String(x) === String(val);
    if (op === "neq") return String(x) !== String(val);
    if (op === "lt") return x < val; if (op === "gte") return x >= val;
    if (op === "is") return val === null ? x === null : x === val;
  });
}
const realFetch = globalThis.fetch;
globalThis.fetch = async (url, opts = {}) => {
  const u = new URL(url);
  if (u.hostname === "api.sendgrid.com") { const b = JSON.parse(opts.body); sent.push({ to: b.personalizations[0].to[0].email, subject: b.subject }); return new Response("", { status: 202 }); }
  if (u.hostname === "api.anthropic.com") {
    const body = JSON.parse(opts.body); const prompt = body.messages[0].content;
    const ni = (prompt.match(/NEEDS IMPROVEMENT/g) || []).length;
    const out = { rating: ni ? "yellow" : "green", headline: `Fake summary: ${ni} items need improvement.`, summary: "This is a fake summary generated by the local test harness. It exercises the whole pipeline without calling Claude.", flags: ni ? [{ title: "Fake flag", detail: "Something was marked needs improvement.", urgency: "soon" }] : [], wins: ["Fake win"] };
    return new Response(JSON.stringify({ content: [{ type: "text", text: JSON.stringify(out) }] }), { status: 200 });
  }
  if (u.pathname.startsWith("/fake-supabase/rest/v1/")) {
    const table = u.pathname.split("/").pop(); const rows = db[table]; const match = parseFilters(u.searchParams);
    const prefer = opts.headers?.Prefer || "";
    if (opts.method === "GET" || !opts.method) {
      let out = rows.filter(match);
      const order = u.searchParams.get("order"); if (order) { const [col, dir] = order.split("."); out.sort((a, b) => (a[col] < b[col] ? -1 : 1) * (dir === "desc" ? -1 : 1)); }
      const limit = u.searchParams.get("limit"); if (limit) out = out.slice(0, +limit);
      return new Response(JSON.stringify(out), { status: 200 });
    }
    if (opts.method === "POST") {
      const body = JSON.parse(opts.body); const conflict = (u.searchParams.get("on_conflict") || "").split(",").filter(Boolean); const out = [];
      for (const r of body) {
        const dup = conflict.length && rows.find((x) => conflict.every((c) => x[c] === r[c]));
        if (dup) { if (prefer.includes("ignore-duplicates")) continue; Object.assign(dup, r); out.push(dup); continue; }
        const row = { id: `${table[0]}${nextId++}`, updated_at: new Date().toISOString(), ...r }; rows.push(row); out.push(row);
      }
      return new Response(JSON.stringify(out), { status: 201 });
    }
    if (opts.method === "PATCH") { const body = JSON.parse(opts.body); const out = rows.filter(match).map((r) => Object.assign(r, body)); return new Response(JSON.stringify(out), { status: 200 }); }
  }
  return realFetch(url, opts);
};

const fns = {};
for (const name of ["checklist", "summarize", "admin", "send-checklists", "send-reminders"]) fns[name] = (await import(`../netlify/functions/${name}.mjs`)).default;
const routes = { "/api/checklist": fns.checklist, "/api/summarize": fns.summarize, "/api/admin": fns.admin, "/api/run/send-checklists": fns["send-checklists"], "/api/run/send-reminders": fns["send-reminders"], "/api/sent": () => new Response(JSON.stringify(sent), { headers: { "content-type": "application/json" } }) };

http.createServer(async (req, res) => {
  const u = new URL(req.url, `http://127.0.0.1:${PORT}`);
  const fn = routes[u.pathname];
  if (fn) {
    const chunks = []; for await (const c of req) chunks.push(c);
    const r = await fn(new Request(u, { method: req.method, headers: req.headers, body: chunks.length ? Buffer.concat(chunks) : undefined }));
    res.writeHead(r.status, Object.fromEntries(r.headers)); res.end(await r.text()); return;
  }
  const file = `public${u.pathname === "/" ? "/index.html" : u.pathname}`;
  if (existsSync(file)) { res.writeHead(200, { "content-type": "text/html" }); res.end(readFileSync(file)); } else { res.writeHead(404); res.end("nope"); }
}).listen(PORT, () => console.log(`fake stack on http://127.0.0.1:${PORT}  (manager: /?b=deleta-skating&key=key1  admin: /admin.html key=adminkey)`));
